version: 2.1
jobs:
  test:
    docker:
      - image: circleci/jruby
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec

  publish:
    docker:
      - image: circleci/jruby
    steps:
      - checkout
      - run: bundle install
      - run:
          name: publish
          command: ./gem_publish.sh

workflows:
  version: 2
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master